variables:
  # Basic
  PROJECT_NAME: api-management-ui
  PROJECT_NAMESPACE: dbp/api-portal

  # Application
  NODE_IMAGE: node:14.17.5
  BUILD_OUTPUT_FOLDER: dist

  # Configs
  JEST_CONFIG_PATH: dbp/.gitlab-ci/jest.config.js
  NPMRC_FILE_PATH: dbp/.gitlab-ci/.npmrc
  SONAR_PROPERTIES_PATH: dbp/.gitlab-ci/sonar.properties
  DOCKER_FILES: api-management-ui=dbp/docker/Dockerfile

  HELM_CHARTS: dbp/helm/$PROJECT_NAME dbp/helm/$PROJECT_NAME-review
  ### Stand deployment
  # префикс для ингрессов стендов
  STAND_INGRESS_PREFIX: api

  # for dev stand
  DEV_STAND_CHART: $PROJECT_NAME-$BUILD_VERSION.tgz
  DEV_STAND_ID: $OCSM_REVIEW_DEV_STAND_ID

  # for review stand
  REVIEW_STAND_CHART: $PROJECT_NAME-review-$BUILD_VERSION.tgz

include:
  - project: dbp/ci_templates
    ref: latest
    file: /pipelines/frontend_npm.yaml
