apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbp-common.fullname" . }}-svc
  labels: {{- include "dbp-common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      targetPort: {{ .Values.application.ports.main }}
      port: {{ .Values.application.ports.main }}
  selector: {{- include "dbp-common.selectorLabels" . | nindent 4 }}