/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A standalone Api Management DTO that contains Swagger OpenAPI specification
 */
export interface ApiSpecificationObject {
  apiId?: string
  /**
   * Swagger OpenAPI specification
   */
  apiSpecification?: object
  versionName?: string
}
