/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessRightsObject } from './accessRightsObject'
import { BasicAuthObject } from './basicAuthObject'
import { LimitObject } from './limitObject'
import { QuotaObject } from './quotaObject'

/**
 * Keys that are used to access services and contain information like      |access rules and rate/quota allowance.
 */
export interface KeyObjectDto {
  /**
   * Access rights list
   */
  accessRights: Array<AccessRightsObject>
  /**
   * Determines if this key is active
   */
  active?: boolean
  basicAuthData: BasicAuthObject
  /**
   * Key identifier
   */
  keyId: string
  limits?: LimitObject
  /**
   * Key name
   */
  name: string
  quotas?: QuotaObject
}
