/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SecurityConfiguration {
  additionalQueryStringParams?: { [key: string]: object }
  apiKey?: string
  apiKeyName?: string
  apiKeyVehicle?: string
  appName?: string
  clientId?: string
  clientSecret?: string
  realm?: string
  scopeSeparator?: string
  useBasicAuthenticationWithAccessCodeGrant?: boolean
}
