/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Api Management DTO that contains Swagger OpenAPI specification
 */
export interface VersionObject {
  /**
   * Swagger OpenAPI specification
   */
  apiSpecification?: object
  /**
   * The expires header, if set, will deprecate access to the API after the time specified.          |The entry here takes the form of: \" YYYY -MM - DD HH : MM \". If this is not set the version will never expire.
   */
  expires?: string
  versionName?: string
}
